In [1]:
#Import the helper functions 'get_all_regions' and 'get_statistics'
#Import the module Query for the main functionality
import os
if not os.path.basename(os.getcwd()) == "datenguide-python":
    os.chdir("..")

from datenguidepy.query_helper import get_regions, get_statistics
from datenguidepy import Query
import pandas as pd
import matplotlib
%matplotlib inline

pd.set_option('display.max_colwidth', 150)

In [2]:
#Regions IDs for Germany states
get_regions().query("level == 'nuts1'")

                              name  level parent
region_id
10                        Saarland  nuts1     DG
11                          Berlin  nuts1     DG
12                     Brandenburg  nuts1     DG
13          Mecklenburg-Vorpommern  nuts1     DG
14                         Sachsen  nuts1     DG
15                  Sachsen-Anhalt  nuts1     DG
16                       Thüringen  nuts1     DG
01              Schleswig-Holstein  nuts1     DG
02                         Hamburg  nuts1     DG
03                   Niedersachsen  nuts1     DG
04                          Bremen  nuts1     DG
05             Nordrhein-Westfalen  nuts1     DG
06                          Hessen  nuts1     DG
07                 Rheinland-Pfalz  nuts1     DG
08         Baden-Württemberg, Land  nuts1     DG
09                          Bayern  nuts1     DG

In [3]:
#Serious accidents involving material damage
# 
#  Explanation for the following statistics (s): 46241 Statistics of road accidents
#  Connotation Serious accidents involving material damage
#  These include "serious accidents involving damage to property in the strict sense" and "other accidents under the influence of intoxicating substances". "Serious accidents involving damage to property in the strict sense" are accidents in which a criminal offense or a misdemeanor (fine) was present, while at least one vehicle due to an accident damage will be towed from the accident site had (this also includes cases under the influence of intoxicating substances).
# "Other accidents under the influence of intoxicating agents" are accidents in which all car involved were still roadworthy and at the same time was at least one accident participant under the influence of intoxicating substances.
# This excludes all other property damage accidents without the influence of intoxicating substances.

In [4]:
#get the data for Serious accidents involving material damage ordered by years
query = Query.region(['01', '02', '03','04', '05','06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16'])
accidents_property_damage = query.add_field('VER056')
query.results(verbose_enums=True).sort_values('year')

,id,name,year,VER056,VER056_source_title_de,VER056_source_valid_from,VER056_source_periodicity,VER056_source_name,VER056_source_url
0,01,Schleswig-Holstein,1995,4464,Statistik der Straßenverkehrsunfälle,1995-12-31T00:00:00,JAEHRLICH,46241,None
1,12,Brandenburg,1995,8825,Statistik der Straßenverkehrsunfälle,1995-12-31T00:00:00,JAEHRLICH,46241,None
0,14,Sachsen,1995,15663,Statistik der Straßenverkehrsunfälle,1995-12-31T00:00:00,JAEHRLICH,46241,None
0,07,Rheinland-Pfalz,1995,9957,Statistik der Straßenverkehrsunfälle,1995-12-31T00:00:00,JAEHRLICH,46241,None
0,08,"Baden-Württemberg, Land",1995,18203,Statistik der Straßenverkehrsunfälle,1995-12-31T00:00:00,JAEHRLICH,46241,None
...,...,...,...,...,...,...,...,...,...
46,03,Niedersachsen,2018,6289,Statistik der Straßenverkehrsunfälle,1995-12-31T00:00:00,JAEHRLICH,46241,None
46,02,Hamburg,2018,2318,Statistik der Straßenverkehrsunfälle,1995-12-31T00:00:00,JAEHRLICH,46241,None
46,01,Schleswig-Holstein,2018,2505,Statistik der Straßenverkehrsunfälle,1995-12-31T00:00:00,JAEHRLICH,46241,None
46,15,Sachsen-Anhalt,2018,1826,Statistik der Straßenverkehrsunfälle,1995-12-31T00:00:00,JAEHRLICH,46241,None
46,16,Thüringen,2018,2188,Statistik der Straßenverkehrsunfälle,1995-12-31T00:00:00,JAEHRLICH,46241,None